image: atlassian/default-image:2

pipelines:
  branches:
    master:
      - step:
          name: Generate static files
          script:
            - git submodule update --init
            - wget https://github.com/gohugoio/hugo/releases/download/v0.48/hugo_0.48_Linux-64bit.deb -O hugo.deb
            - dpkg -i hugo.deb
            - /usr/local/bin/hugo -v -D
          artifacts:
            - public/**
      - step:
          name: Deploy to S3
          image: atlassian/pipelines-awscli
          script:
            - aws s3 sync --acl public-read --delete public/ s3://akhilvelagapudi.com
