baseURL = "https://akhilvelagapudi.com"
title = "Akhil Velagapudi"
theme = "hyde"

[params]
    author = "Akhil Velagapudi"
    bitbucket = "akhilles97"
    description = "I’m a **software engineer** currently working in the Bay Area. I enjoy back-end development and chess programming!"

[menu]
  [[menu.main]]
    name = "LinkedIn"
    url = "https://linkedin.com/in/akhil-velagapudi"
  [[menu.main]]
    name = "GitHub"
    url = "https://github.com/akhilles"